def fact(n: Int): Int =
  if (n == 0){
    (new RuntimeException).getStackTrace.foreach(println)
    1
  }
  else n * fact(n - 1)

def tailFact(n: Int, result: Int): Int =
  if (n == 0) {
    (new RuntimeException).getStackTrace.foreach(println)
    result
  }
  else tailFact(n - 1, result * n)


tailFact(4,1)
println("------------------------")
fact(4)

/*
$line24.$read$$iw$$iw$.tailFact(<console>:13)
$line25.$read$$iw$$iw$.<init>(<console>:13)
$line25.$read$$iw$$iw$.<clinit>(<console>)
$line25.$eval$.$print$lzycompute(<console>:7)
$line25.$eval$.$print(<console>:6)
$line25.$eval.$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:732)
scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:993)
scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:564)
scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:32)
scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:33)
scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:563)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:590)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:560)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperImpl.processChunk(ILoopWrapperImpl.scala:41)
org.jetbrains.jps.incremental.scala.local.worksheet.compatibility.JavaILoopWrapperFactory.loadReplWrapperAndRun(JavaILoopWrapperFactory.java:87)
org.jetbrains.jps.incremental.scala.local.worksheet.compatibility.JavaILoopWrapperFactory.loadReplWrapperAndRun(JavaILoopWrapperFactory.java:51)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$3(ILoopWrapperFactoryHandler.scala:57)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler$.org$jetbrains$jps$incremental$scala$local$worksheet$ILoopWrapperFactoryHandler$$withFilteredPath(ILoopWrapperFactoryHandler.scala:132)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$2(ILoopWrapperFactoryHandler.scala:54)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$2$adapted(ILoopWrapperFactoryHandler.scala:43)
scala.Option.foreach(Option.scala:257)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.loadReplWrapperAndRun(ILoopWrapperFactoryHandler.scala:43)
org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer.loadAndRun(WorksheetServer.scala:29)
org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:85)
org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:26)
org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
res0: Int = 24
------------------------
$line23.$read$$iw$$iw$.fact(<console>:13)
$line23.$read$$iw$$iw$.fact(<console>:16)
$line23.$read$$iw$$iw$.fact(<console>:16)
$line23.$read$$iw$$iw$.fact(<console>:16)
$line23.$read$$iw$$iw$.fact(<console>:16)
$line27.$read$$iw$$iw$.<init>(<console>:13)
$line27.$read$$iw$$iw$.<clinit>(<console>)
$line27.$eval$.$print$lzycompute(<console>:7)
$line27.$eval$.$print(<console>:6)
$line27.$eval.$print(<console>)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:732)
scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:993)
scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:564)
scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:32)
scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:33)
scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:563)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:590)
scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:560)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperImpl.processChunk(ILoopWrapperImpl.scala:41)
org.jetbrains.jps.incremental.scala.local.worksheet.compatibility.JavaILoopWrapperFactory.loadReplWrapperAndRun(JavaILoopWrapperFactory.java:87)
org.jetbrains.jps.incremental.scala.local.worksheet.compatibility.JavaILoopWrapperFactory.loadReplWrapperAndRun(JavaILoopWrapperFactory.java:51)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$3(ILoopWrapperFactoryHandler.scala:57)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler$.org$jetbrains$jps$incremental$scala$local$worksheet$ILoopWrapperFactoryHandler$$withFilteredPath(ILoopWrapperFactoryHandler.scala:132)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$2(ILoopWrapperFactoryHandler.scala:54)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.$anonfun$loadReplWrapperAndRun$2$adapted(ILoopWrapperFactoryHandler.scala:43)
scala.Option.foreach(Option.scala:257)
org.jetbrains.jps.incremental.scala.local.worksheet.ILoopWrapperFactoryHandler.loadReplWrapperAndRun(ILoopWrapperFactoryHandler.scala:43)
org.jetbrains.jps.incremental.scala.local.worksheet.WorksheetServer.loadAndRun(WorksheetServer.scala:29)
org.jetbrains.jps.incremental.scala.remote.Main$.make(Main.scala:85)
org.jetbrains.jps.incremental.scala.remote.Main$.nailMain(Main.scala:26)
org.jetbrains.jps.incremental.scala.remote.Main.nailMain(Main.scala)
sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(Method.java:498)
com.martiansoftware.nailgun.NGSession.run(NGSession.java:319)
res2: Int = 24
 */
